# <font color='black'>Регрессионный анализ: панельные данные и каузальность, 2026 </font>
## <font color='black'> Метод инструментальных переменных </font>

Рассмотрим пример применения метода инструментальных переменных из статьи Hansford T. G., Gomez B. T. (2010) Estimating the Electoral Effects of Voter Turnout.The American Political Science Review, Vol. 104, No. 2, pp. 268 - 288. (статью можете скачать по ссылке https://disk.yandex.ru/i/kIc9Ed09_vaX8w).

Ниже представлено краткое описание данных:

* Year - Election Year
* FIPS_County - FIPS County Code
* DemVoteShare2 - Democratic President Candidate’s Vote Share
* Turnout - turnout (in percentage)   
* DNormPrcp_KRIG - Election day rainfall differenced from normal rain for the day

Откроем массив и оставим только необходимые для анализа переменные:

In [ ]:
import pandas as pd
import numpy as np
import numpy.linalg as la
import statsmodels.formula.api as smf
!pip install linearmodels
from linearmodels import IV2SLS

Requirement already satisfied: linearmodels in /usr/local/lib/python3.12/dist-packages (7.0)
Requirement already satisfied: numpy<3,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (2.0.2)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (2.2.2)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (1.16.3)
Requirement already satisfied: statsmodels>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (0.14.6)
Requirement already satisfied: mypy_extensions>=0.4 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (1.1.0)
Requirement already satisfied: pyhdfe>=0.1 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (0.2.0)
Requirement already satisfied: formulaic>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (1.2.1)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.2.1->linearmodels) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.2.1->linearmodels) (2.20.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.2.1->linearmodels) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.2.1->linearmodels) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->linearmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->linearmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->linearmodels) (2026.1)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.13.0->linearmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.13.0->linearmodels) (26.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->linearmodels) (1.17.0)

In [ ]:
IVdata = pd.read_csv('IVdata.csv')
IVdata_short = IVdata[['Year', 'FIPS_County', 'Turnout', 'DemVoteShare2', 'DNormPrcp_KRIG']].dropna()
IVdata_short.head()

   Year  FIPS_County   Turnout  DemVoteShare2  DNormPrcp_KRIG
0  1948         4021  27.17562       61.54376       -0.025283
1  1948         4019  44.74918       51.04443       -0.010943
2  1948         4009  51.46835       63.88889       -0.035849
3  1948         4025  55.56316       50.87096       -0.044717
4  1948         4013  42.93417       52.53817       -0.025660

Оценим предварительную модель, не применяя метод IV. Какие источники эндогенности присутствуют в данном случае? Можно ли доверять полученным результатам?

In [ ]:
m1 = smf.ols(formula='DemVoteShare2 ~ Turnout + C(Year)', data=IVdata_short).fit(cov_type='cluster', cov_kwds={'groups': IVdata_short['FIPS_County']})
print(m1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          DemVoteShare2   R-squared:                       0.281
Model:                            OLS   Adj. R-squared:                  0.280
Method:                 Least Squares   F-statistic:                     5416.
Date:                Sun, 10 May 2026   Prob (F-statistic):               0.00
Time:                        22:06:54   Log-Likelihood:            -1.0339e+05
No. Observations:               27401   AIC:                         2.068e+05
Df Residuals:                   27386   BIC:                         2.069e+05
Df Model:                          14
Covariance Type:              cluster
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept          59.0855      1.240     47.662      0.000      56.656      61.515
C(Year)[T.1952]   -10.2149      0.238    -42.864      0.000     -10.682      -9.748
C(Year)[T.1956]    -8.7562      0.205    -42.627      0.000      -9.159      -8.354
C(Year)[T.1960]    -3.8616      0.300    -12.864      0.000      -4.450      -3.273
C(Year)[T.1964]    10.8510      0.235     46.159      0.000      10.390      11.312
C(Year)[T.1968]    -6.4771      0.206    -31.470      0.000      -6.881      -6.074
C(Year)[T.1972]   -13.7490      0.257    -53.463      0.000     -14.253     -13.245
C(Year)[T.1976]    -0.3671      0.195     -1.879      0.060      -0.750       0.016
C(Year)[T.1980]   -10.3462      0.240    -43.087      0.000     -10.817      -9.876
C(Year)[T.1984]   -13.1342      0.254    -51.798      0.000     -13.631     -12.637
C(Year)[T.1988]    -5.7121      0.256    -22.292      0.000      -6.214      -5.210
C(Year)[T.1992]    -0.3274      0.270     -1.210      0.226      -0.858       0.203
C(Year)[T.1996]    -1.1934      0.327     -3.648      0.000      -1.834      -0.552
C(Year)[T.2000]    -9.0125      0.350    -25.740      0.000      -9.699      -8.326
Turnout            -0.1572      0.019     -8.287      0.000      -0.194      -0.120
==============================================================================
Omnibus:                      264.595   Durbin-Watson:                   1.364
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              288.516
Skew:                           0.209   Prob(JB):                     2.24e-63
Kurtosis:                       3.280   Cond. No.                         959.
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

Сначала попробуем реализовать метод IV последовательно. Оценим модель первого шага:

In [ ]:
stage1 = smf.ols('Turnout ~ DNormPrcp_KRIG + C(Year)', data=IVdata_short).fit(cov_type='cluster', cov_kwds={'groups': IVdata_short['FIPS_County']})
print(stage1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                Turnout   R-squared:                       0.226
Model:                            OLS   Adj. R-squared:                  0.226
Method:                 Least Squares   F-statistic:                     1526.
Date:                Sun, 10 May 2026   Prob (F-statistic):               0.00
Time:                        22:06:54   Log-Likelihood:                -99833.
No. Observations:               27401   AIC:                         1.997e+05
Df Residuals:                   27386   BIC:                         1.998e+05
Df Model:                          14
Covariance Type:              cluster
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept          61.6937      0.217    284.686      0.000      61.269      62.118
C(Year)[T.1952]    11.1040      0.122     90.845      0.000      10.864      11.344
C(Year)[T.1956]     9.5099      0.147     64.602      0.000       9.221       9.798
C(Year)[T.1960]    14.0741      0.159     88.240      0.000      13.762      14.387
C(Year)[T.1964]     8.0272      0.172     46.723      0.000       7.690       8.364
C(Year)[T.1968]     4.1738      0.176     23.718      0.000       3.829       4.519
C(Year)[T.1972]     5.1736      0.197     26.257      0.000       4.787       5.560
C(Year)[T.1976]     3.7283      0.210     17.723      0.000       3.316       4.141
C(Year)[T.1980]     2.8924      0.226     12.778      0.000       2.449       3.336
C(Year)[T.1984]     0.9526      0.209      4.560      0.000       0.543       1.362
C(Year)[T.1988]    -1.2560      0.215     -5.836      0.000      -1.678      -0.834
C(Year)[T.1992]     1.1629      0.232      5.007      0.000       0.708       1.618
C(Year)[T.1996]    -3.6629      0.242    -15.133      0.000      -4.137      -3.188
C(Year)[T.2000]    -1.9532      0.264     -7.386      0.000      -2.472      -1.435
DNormPrcp_KRIG      2.1072      0.287      7.342      0.000       1.545       2.670
==============================================================================
Omnibus:                      658.764   Durbin-Watson:                   1.204
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1548.330
Skew:                          -0.041   Prob(JB):                         0.00
Kurtosis:                       4.162   Cond. No.                         15.0
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

Выведем частную F-статистику для инструмента для того, чтобы проверить гипотезу о силе инструмента. Для того, чтобы можно было утверждать, что инструмент не является слабым, F-статистика должна превышать 10

In [ ]:
stage1_short = smf.ols('Turnout ~ C(Year)', data=IVdata_short).fit(cov_type='cluster', cov_kwds={'groups': IVdata_short['FIPS_County']})

ssr_full = stage1.ssr
ssr_restricted = stage1_short.ssr
dif = 1
df_full = stage1.df_resid

f_statistic = ((ssr_restricted - ssr_full) / dif) / (ssr_full / df_full)
print(f"Частная F-статистика: {f_statistic:.2f}")

Частная F-статистика: 51.02

Либо используем тест Вальда (Wald test):

In [ ]:
wald_result = stage1.wald_test('DNormPrcp_KRIG = 0')
print(f"Статистика теста Вальда: {wald_result.statistic[0][0]:.2f}, p-value: {wald_result.pvalue:.4f}")

Статистика теста Вальда: 53.91, p-value: 0.0000

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(

Реализуем второй шаг метода инструментальных переменных, предварительно сохранив предсказанные значения из первой модели (stage1)

In [ ]:
IVdata_short['fitted'] = stage1.predict()

stage2 = smf.ols('DemVoteShare2 ~ fitted + C(Year)', data=IVdata_short).fit(cov_type='cluster', cov_kwds={'groups': IVdata_short['FIPS_County']})
print(stage2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          DemVoteShare2   R-squared:                       0.267
Model:                            OLS   Adj. R-squared:                  0.267
Method:                 Least Squares   F-statistic:                     5679.
Date:                Sun, 10 May 2026   Prob (F-statistic):               0.00
Time:                        22:06:55   Log-Likelihood:            -1.0364e+05
No. Observations:               27401   AIC:                         2.073e+05
Df Residuals:                   27386   BIC:                         2.074e+05
Df Model:                          14
Covariance Type:              cluster
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept          26.9099     10.950      2.458      0.014       5.449      48.371
C(Year)[T.1952]   -15.8325      1.925     -8.223      0.000     -19.606     -12.059
C(Year)[T.1956]   -13.6555      1.664     -8.206      0.000     -16.917     -10.394
C(Year)[T.1960]   -11.0939      2.473     -4.485      0.000     -15.942      -6.246
C(Year)[T.1964]     6.8371      1.385      4.937      0.000       4.123       9.551
C(Year)[T.1968]    -8.5142      0.740    -11.511      0.000      -9.964      -7.065
C(Year)[T.1972]   -16.4728      0.961    -17.139      0.000     -18.357     -14.589
C(Year)[T.1976]    -2.1115      0.636     -3.321      0.001      -3.358      -0.865
C(Year)[T.1980]   -11.6959      0.535    -21.849      0.000     -12.745     -10.647
C(Year)[T.1984]   -13.5147      0.288    -46.859      0.000     -14.080     -12.949
C(Year)[T.1988]    -4.9514      0.345    -14.340      0.000      -5.628      -4.275
C(Year)[T.1992]    -1.0079      0.375     -2.690      0.007      -1.742      -0.274
C(Year)[T.1996]     0.8107      0.715      1.133      0.257      -0.591       2.213
C(Year)[T.2000]    -8.1302      0.428    -18.985      0.000      -8.970      -7.291
fitted              0.3631      0.177      2.056      0.040       0.017       0.709
==============================================================================
Omnibus:                      293.251   Durbin-Watson:                   1.352
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              340.745
Skew:                           0.200   Prob(JB):                     1.02e-74
Kurtosis:                       3.372   Cond. No.                     1.09e+04
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The condition number is large, 1.09e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Реализуем метод IV автоматически:

In [ ]:
iv_model = IV2SLS.from_formula('DemVoteShare2 ~ 1 + C(Year) + [Turnout ~ DNormPrcp_KRIG]', data=IVdata_short).fit(cov_type='clustered', clusters=IVdata_short['FIPS_County'])
print(iv_model)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:          DemVoteShare2   R-squared:                      0.1302
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1297
No. Observations:               27401   F-statistic:                 7.564e+04
Date:                Sun, May 10 2026   P-value (F-stat)                0.0000
Time:                        22:06:56   Distribution:                 chi2(14)
Cov. Estimator:             clustered

                                Parameter Estimates
===================================================================================
                 Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------
Intercept           26.910     11.587     2.3225     0.0202      4.2005      49.619
C(Year)[T.1952]    -15.832     2.0348    -7.7809     0.0000     -19.821     -11.844
C(Year)[T.1956]    -13.656     1.7608    -7.7552     0.0000     -17.107     -10.204
C(Year)[T.1960]    -11.094     2.6172    -4.2388     0.0000     -16.224     -5.9642
C(Year)[T.1964]     6.8371     1.4625     4.6750     0.0000      3.9707      9.7035
C(Year)[T.1968]    -8.5142     0.7810    -10.901     0.0000     -10.045     -6.9834
C(Year)[T.1972]    -16.473     1.0143    -16.241     0.0000     -18.461     -14.485
C(Year)[T.1976]    -2.1115     0.6757    -3.1251     0.0018     -3.4358     -0.7872
C(Year)[T.1980]    -11.696     0.5746    -20.354     0.0000     -12.822     -10.570
C(Year)[T.1984]    -13.515     0.3028    -44.635     0.0000     -14.108     -12.921
C(Year)[T.1988]    -4.9514     0.3584    -13.817     0.0000     -5.6538     -4.2490
C(Year)[T.1992]    -1.0079     0.3983    -2.5307     0.0114     -1.7885     -0.2273
C(Year)[T.1996]     0.8107     0.7557     1.0727     0.2834     -0.6705      2.2918
C(Year)[T.2000]    -8.1302     0.4455    -18.249     0.0000     -9.0034     -7.2570
Turnout             0.3631     0.1869     1.9426     0.0521     -0.0032      0.7294
===================================================================================

Endogenous: Turnout
Instruments: DNormPrcp_KRIG
Clustered Covariance (One-Way)
Debiased: False
Num Clusters: 1964

Проверим сопоставимость оценок OLS и TSLS при помощи теста Ву-Хаусмана:

In [ ]:
print(iv_model.wu_hausman())

Wu-Hausman test of exogeneity
H0: All endogenous variables are exogenous
Statistic: 10.6776
P-value: 0.0011
Distributed: F(1,27385)

Результаты теста Саргана в данном случае недоступны, как мы видим. Причина этому - точная идентификация (количество инструментов = количество эндогенных предикторов)

In [ ]:
if hasattr(iv_model, 'sargan'):
    print(f"Статистика теста Хансена: {iv_model.sargan.stat:.3f}")
    print(f"p-value: {iv_model.sargan.pval:.3f}")

Статистика теста Хансена: nan
p-value: nan

## Практикум: часть 2

Откроем массив IV_data2.Rda

Ниже представлено краткое описание данных для этого классического примера из эконометрики оценивания эффекта образования на заработную плату посредством инструментальных переменных

* wage - outcome variable - natural logarithm (wage)
* education - years of education
* gender - male/female
* fcollege - Father's education: "yes" stands for higher education
* mcollege - Mother's education: "yes" stands for higher education
* ethnicity - Afro-American / Latin American / other
* urban (dummy-variable: 1 - urban, 0 - rural)
* distance - distance from college

In [ ]:
!pip install pyreadr
import pyreadr as pyreadr

Requirement already satisfied: pyreadr in /usr/local/lib/python3.12/dist-packages (0.5.6)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from pyreadr) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.0->pyreadr) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.0->pyreadr) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.0->pyreadr) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.0->pyreadr) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadr) (1.17.0)

In [ ]:
dta2 = pyreadr.read_r('IV_data2.Rda')
dta2 = dta2[None]
dta2

          gender ethnicity fcollege mcollege  urban  wage  distance  education
rownames
1           male     other      yes       no    1.0  8.09       0.2       12.0
2         female     other       no       no    1.0  8.09       0.2       12.0
3           male     other       no       no    1.0  8.09       0.2       12.0
4           male      afam       no       no    1.0  8.09       0.2       12.0
5         female     other       no       no    1.0  8.09       0.4       13.0
...          ...       ...      ...      ...    ...   ...       ...        ...
9391        male      afam       no       no    0.0  8.89       0.8       13.0
9401        male      afam       no       no    0.0  8.89       0.8       15.0
9411        male     other       no       no    0.0  8.89       0.8       12.0
9421        male      afam      yes      yes    0.0  8.89       0.8       16.0
9431        male      afam       no      yes    0.0  8.89       0.8       13.0

[4739 rows x 8 columns]

Приведите необходимые преобразования переменных при необходимости и оцените при помощи 2МНК модель wage на education. Остальные переменные разделите на две подгруппы: контрольные переменные и инструментальные переменные. Выберите несколько инструментальных переменных, чтобы создалась ситуация чрезмерной идентификации.

Проинтерпретируйте полученные результаты, сравните с оценками соответствующей модели без инструментальных переменных.

Реализуйте все необходимые диагностики для модели с инструментальными переменными (тест на слабость инструментов, тест Ву-Хаусмана и тест Хансена) и проинтерпретируйте полученные результаты